name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/URLShortenerBackend

            echo "Pulling latest backend code..."
            git pull origin main

            echo "Building Spring Boot application..."
            mvn clean package -DskipTests

            echo "Stopping old Spring Boot application..."
            pkill -f 'java -jar target/url_shortener-0.0.1-SNAPSHOT.jar' || true

            sleep 3echo "Stopping old Spring Boot application..."
            PID=$(pgrep -f 'java -jar target/url_shortener-0.0.1-SNAPSHOT.jar' || true)
            
            if [ -n "$PID" ]; then
              echo "Stopping Spring Boot process: $PID"
              kill "$PID" || true
              sleep 5
            else
              echo "No old Spring Boot process found."
            fi

            echo "Starting new Spring Boot application..."
            nohup java -jar target/url_shortener-0.0.1-SNAPSHOT.jar > backend.log 2>&1 &

            echo "Backend deployment completed!"
